version: '3.8'

services:
  frontend:
    build:
      context: ./client
    ports:
      - "3001:80"
    container_name: chitShTools-frontend
    depends_on:
      - backend
    links:
      - backend

  backend:
    build:
      context: ./server
    ports:
      - "3000:3000"
    container_name: chitShTools-backend